/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SellerService } from "../seller.service";
import { SellerCreateInput } from "./SellerCreateInput";
import { Seller } from "./Seller";
import { SellerFindManyArgs } from "./SellerFindManyArgs";
import { SellerWhereUniqueInput } from "./SellerWhereUniqueInput";
import { SellerUpdateInput } from "./SellerUpdateInput";
import { OfferFindManyArgs } from "../../offer/base/OfferFindManyArgs";
import { Offer } from "../../offer/base/Offer";
import { OfferWhereUniqueInput } from "../../offer/base/OfferWhereUniqueInput";

export class SellerControllerBase {
  constructor(protected readonly service: SellerService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Seller })
  async createSeller(@common.Body() data: SellerCreateInput): Promise<Seller> {
    return await this.service.createSeller({
      data: data,
      select: {
        createdAt: true,
        id: true,
        role: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Seller] })
  @ApiNestedQuery(SellerFindManyArgs)
  async sellers(@common.Req() request: Request): Promise<Seller[]> {
    const args = plainToClass(SellerFindManyArgs, request.query);
    return this.service.sellers({
      ...args,
      select: {
        createdAt: true,
        id: true,
        role: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Seller })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async seller(
    @common.Param() params: SellerWhereUniqueInput
  ): Promise<Seller | null> {
    const result = await this.service.seller({
      where: params,
      select: {
        createdAt: true,
        id: true,
        role: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Seller })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSeller(
    @common.Param() params: SellerWhereUniqueInput,
    @common.Body() data: SellerUpdateInput
  ): Promise<Seller | null> {
    try {
      return await this.service.updateSeller({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          role: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Seller })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSeller(
    @common.Param() params: SellerWhereUniqueInput
  ): Promise<Seller | null> {
    try {
      return await this.service.deleteSeller({
        where: params,
        select: {
          createdAt: true,
          id: true,
          role: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/offers")
  @ApiNestedQuery(OfferFindManyArgs)
  async findOffers(
    @common.Req() request: Request,
    @common.Param() params: SellerWhereUniqueInput
  ): Promise<Offer[]> {
    const query = plainToClass(OfferFindManyArgs, request.query);
    const results = await this.service.findOffers(params.id, {
      ...query,
      select: {
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        offerDetails: true,

        product: {
          select: {
            id: true,
          },
        },

        seller: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/offers")
  async connectOffers(
    @common.Param() params: SellerWhereUniqueInput,
    @common.Body() body: OfferWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      offers: {
        connect: body,
      },
    };
    await this.service.updateSeller({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/offers")
  async updateOffers(
    @common.Param() params: SellerWhereUniqueInput,
    @common.Body() body: OfferWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      offers: {
        set: body,
      },
    };
    await this.service.updateSeller({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/offers")
  async disconnectOffers(
    @common.Param() params: SellerWhereUniqueInput,
    @common.Body() body: OfferWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      offers: {
        disconnect: body,
      },
    };
    await this.service.updateSeller({
      where: params,
      data,
      select: { id: true },
    });
  }
}
