/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Offer } from "./Offer";
import { OfferCountArgs } from "./OfferCountArgs";
import { OfferFindManyArgs } from "./OfferFindManyArgs";
import { OfferFindUniqueArgs } from "./OfferFindUniqueArgs";
import { CreateOfferArgs } from "./CreateOfferArgs";
import { UpdateOfferArgs } from "./UpdateOfferArgs";
import { DeleteOfferArgs } from "./DeleteOfferArgs";
import { Customer } from "../../customer/base/Customer";
import { Product } from "../../product/base/Product";
import { Seller } from "../../seller/base/Seller";
import { OfferService } from "../offer.service";
@graphql.Resolver(() => Offer)
export class OfferResolverBase {
  constructor(protected readonly service: OfferService) {}

  async _offersMeta(
    @graphql.Args() args: OfferCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Offer])
  async offers(@graphql.Args() args: OfferFindManyArgs): Promise<Offer[]> {
    return this.service.offers(args);
  }

  @graphql.Query(() => Offer, { nullable: true })
  async offer(
    @graphql.Args() args: OfferFindUniqueArgs
  ): Promise<Offer | null> {
    const result = await this.service.offer(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Offer)
  async createOffer(@graphql.Args() args: CreateOfferArgs): Promise<Offer> {
    return await this.service.createOffer({
      ...args,
      data: {
        ...args.data,

        customer: args.data.customer
          ? {
              connect: args.data.customer,
            }
          : undefined,

        product: args.data.product
          ? {
              connect: args.data.product,
            }
          : undefined,

        seller: args.data.seller
          ? {
              connect: args.data.seller,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Offer)
  async updateOffer(
    @graphql.Args() args: UpdateOfferArgs
  ): Promise<Offer | null> {
    try {
      return await this.service.updateOffer({
        ...args,
        data: {
          ...args.data,

          customer: args.data.customer
            ? {
                connect: args.data.customer,
              }
            : undefined,

          product: args.data.product
            ? {
                connect: args.data.product,
              }
            : undefined,

          seller: args.data.seller
            ? {
                connect: args.data.seller,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Offer)
  async deleteOffer(
    @graphql.Args() args: DeleteOfferArgs
  ): Promise<Offer | null> {
    try {
      return await this.service.deleteOffer(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Customer, {
    nullable: true,
    name: "customer",
  })
  async getCustomer(@graphql.Parent() parent: Offer): Promise<Customer | null> {
    const result = await this.service.getCustomer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Product, {
    nullable: true,
    name: "product",
  })
  async getProduct(@graphql.Parent() parent: Offer): Promise<Product | null> {
    const result = await this.service.getProduct(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Seller, {
    nullable: true,
    name: "seller",
  })
  async getSeller(@graphql.Parent() parent: Offer): Promise<Seller | null> {
    const result = await this.service.getSeller(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
